### PR TITLE
Much Better and Cleaner-Simplified Feedback Buttons

### PR DESCRIPTION
**Pull request by Tpixelminer**
+ Changed  “Get Started” to “Log In” on the upper right of index.ejs

+Simplified Feedback buttons to a hover drop down menu. You can change
the color if you want. It also may be a little buggy.

-Added text and cleaned code from previous commit.

### CODE REVIEW

**Comment by Tpixelminer** [comment]
3 months later

**Comment by RobotXLabs** [comment]
@Tpixelminer shhhh

**Comment by Tpixelminer** [comment]
@RobotXLabs 😧

**Comment by nywillb** [comment]
@Tpixelminer, have you considered using the [Bootstrap `btn-dropdown`](http://getbootstrap.com/components/#btn-dropdowns) for this?

**Comment by Tpixelminer** [comment]
I definitely didn't consider using bootstrap back in December.................. # #

**Comment by nywillb** [comment]
@Tpixelminer:
> >@Tpixelminer shhhh
>
>_- @RobotXLabs_

**Comment by nywillb** [comment]
This feature has been added outside of this pull request. Sorry @Tpixelminer, closing 9 months too late.

**Pull request closed without merging**
